name: icenet2
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cartopy
  - dask
  - distributed
  - h5py
  - hdf4
  - hdf5
  - iris
  - netcdf4
  - plotly
  - pip
  - python==3.8
  - setuptools
  - tensorboard
  - tensorflow
  - wheel
  - xarray
  - pip:
    - cdsapi
    - dm-tree
    - tensorflow-probability
