name: icenet2
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - dask
  - distributed
  - h5py
  - hdf4
  - hdf5
  - plotly
  - python>=3.7
  - tensorboard
  - tensorflow
  - xarray
  - pip:
    - dm-tree
    - tensorflow-probability
